#!/bin/bash
set -euxo pipefail

# Ensure previous resources exist
kubectl -n agentgateway-system get httproute github-mcp-route
kubectl -n agentgateway-system get httproute slack-mcp-route

echo "Challenge 5 setup complete"
