#!/bin/bash
set -euxo pipefail

export CTX_CLUSTER1=k3d-cluster-1
export CTX_CLUSTER2=k3d-cluster-2

for i in $(seq 1 10); do
  kubectl --context=$CTX_CLUSTER1 exec -n finance deploy/curl -- \
    curl -s accounts.accounts.svc.cluster.local:8080
done > /root/multicluster-results.txt

cat /root/multicluster-results.txt
