#!/bin/bash
set -euxo pipefail

export CTX_CLUSTER1=k3d-cluster-1
export CTX_CLUSTER2=k3d-cluster-2

kubectl --context=$CTX_CLUSTER1 get pods -n istio-system
kubectl --context=$CTX_CLUSTER2 get pods -n istio-system

echo "Two-cluster Istio ambient mesh verified on $(date)" > /root/environment-verified.txt
