#!/bin/bash
set -euo pipefail

helm upgrade -i --create-namespace \
  --namespace agentgateway-system \
  --version v2.2.1 agentgateway-crds \
  oci://ghcr.io/kgateway-dev/charts/agentgateway-crds

helm upgrade -i \
  -n agentgateway-system \
  --version v2.2.1 agentgateway \
  oci://ghcr.io/kgateway-dev/charts/agentgateway

kubectl wait --for=condition=Ready pods --all -n agentgateway-system --timeout=120s
