#!/bin/bash
set -euxo pipefail

export CTX_CLUSTER1=k3d-cluster-1
export CTX_CLUSTER2=k3d-cluster-2

for ctx in $CTX_CLUSTER1 $CTX_CLUSTER2; do
  kubectl --context=$ctx label namespace finance istio.io/dataplane-mode=ambient
  kubectl --context=$ctx label namespace accounts istio.io/dataplane-mode=ambient
done

sleep 5

kubectl --context=$CTX_CLUSTER1 exec -n finance deploy/curl -- curl -s accounts.accounts.svc.cluster.local:8080
kubectl --context=$CTX_CLUSTER2 exec -n finance deploy/curl -- curl -s accounts.accounts.svc.cluster.local:8080
